services:
  bot:
    image: ghcr.io/luxqw/vexel-music-bot:latest
    container_name: vexel-music-bot
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./bot:/app/bot
    working_dir: /app
    restart: unless-stopped
    command: ["python3", "main.py"]
