name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract version from git tag
      id: vars
      run: |
        if [[ "${GITHUB_REF}" == refs/tags/v* ]]; then
          VERSION="${GITHUB_REF#refs/tags/v}"
        else
          VERSION="latest"
        fi
        echo "version=$VERSION" >> $GITHUB_OUTPUT

    - name: Build and push Docker image
      run: |
        IMAGE=ghcr.io/${{ github.repository_owner }}/vexel-music-bot
        docker build -t $IMAGE:${{ steps.vars.outputs.version }} -t $IMAGE:latest .
        docker push $IMAGE:${{ steps.vars.outputs.version }}
        docker push $IMAGE:latest
