name: Docker Image CI (dev)

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push Docker image (dev)
        run: |
          IMAGE=ghcr.io/${{ github.repository_owner }}/vexel-music-bot
          docker build -t $IMAGE:dev -t $IMAGE:dev-latest .
          docker push $IMAGE:dev
          docker push $IMAGE:dev-latest

      - name: Notify Discord
        if: always()
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          STATUS_MSG=""
          COLOR=16711680
          if [[ "${{ job.status }}" == "success" ]]; then
            STATUS_MSG="✅ Dev Build Completed Successfully!"
            COLOR=65280
          else
            STATUS_MSG="❌ Dev Build Failed!"
          fi

          curl -H "Content-Type: application/json" \
               -d "{
                    \"embeds\": [{
                        \"title\": \"${STATUS_MSG}\",
                        \"description\": \"**Branch:** dev\n**Commit:** [${{ github.sha }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }})\",
                        \"url\": \"https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}\",
                        \"color\": ${COLOR}
                    }]
                }" \
               $DISCORD_WEBHOOK
