name: Release Notify (dev)

on:
  release:
    types: [published]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Notify Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          curl -H "Content-Type: application/json" \
               -d "{
                    \"embeds\": [{
                        \"title\": \"🚀 New Release (dev) Published!\",
                        \"description\": \"**Release Name:** ${{ github.event.release.name }}\n**Tag:** ${{ github.event.release.tag_name }}\n**Author:** ${{ github.event.release.author.login }}\n**Release URL:** [View Release](${{ github.event.release.html_url }})\",
                        \"url\": \"${{ github.event.release.html_url }}\",
                        \"color\": 3447003
                    }]
                }" \
               $DISCORD_WEBHOOK
